const sidebars = {
  docs: [
    'index',
    {
      type: 'category',
      label: '产品简介',
      link: {
        type: 'generated-index',
        title: '产品介绍',
        description: '了解 Gpushare 产品及理念！',
        //slug: '/product',
      },
      collapsed: false,
      items: [
        'product/price',
        'product/agreement',
        'product/privacy-policy',
        'product/owner-agreement',
      ],
    },
    {
      type: 'category',
      label: '快速入门',
      link: {
        type: 'generated-index',
        //slug: '/product',
      },
      collapsed: false,
      items: [
        'getting-started/quickstart',
        'getting-started/car',
        'getting-started/login_instance',
        'getting-started/login_windows',
        'getting-started/command'
      ],
    },
    {
      type: 'category',
      label: '白嫖大法',
      link: {
        type: 'generated-index',
        //slug: '/product',
      },
      collapsed: false,
      items: [
        'free_ride/coupon',
        'free_ride/cash',
      ],
    },
    {
      type: 'category',
      label: '实例管理',
      link: {
        type: 'generated-index',
        //slug: '/product',
      },
      collapsed: false,
      items: [
        'instance/environment',
        'instance/manage',
        'instance/image',
        'instance/team',
        'instance/migration'
      ],
    },
    {
      type: 'category',
      label: '数据管理',
      link: {
        type: 'generated-index',
        //slug: '/product',
      },
      collapsed: false,
      items: [
        'data/storage',
        'data/upload',
        'data/download',
        'data/datause',
        'data/public_disk'
      ],
    },
  ],
  practice: [
    {
      type: 'autogenerated',
      dirName: 'best_practices',
    },
  ],
  faq: [
    {
      type: 'autogenerated',
      dirName: 'faq',
    },
  ],
};
module.exports = sidebars;